[package]
name = "rengine"
version = "0.1.0"
authors = ["Adrian Revk <ra.dubouchet@gmail.com>"]
build = "src/build.rs"

[dependencies]
chrono = "*"
log = "*"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs.git"
default-features = false